#!/bin/bash

#SBATCH --job-name=train_hyperopt
#SBATCH --output=/home/mcs001/20181133/CLAM/job_logs/hyperopt_%j.txt
#SBATCH --partition=mcs.gpu.q
#SBATCH --time=2:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=3
#SBATCH --mem-per-cpu=8G
#SBATCH --gpus=1

source /cm/shared/apps/Anaconda/2021.11/pth3.9/etc/profile.d/conda.sh
module load CUDA/11.7.0
conda activate thesis-conda-env6

# Open WSI-finetuning project
cd /home/mcs001/20181133/CLAM/

export CUDA_VISIBLE_DEVICES=0

# Arguments passed from Bayesian optimization script
LR=$1               # Learning rate
REG=$2              # Regularization
WINDOW_SIZE=$3      # Window size
USE_GRID=$4         # 1 = Use grid, 0 = Don't use grid
USE_BLOCK=$5        # 1 = Use block, 0 = Don't use block
EXP_CODE=$6         # Experiment code for logging
RESULT_FILE=$7      # File to save the metric (validation loss)

# Set optional arguments for --use_grid and --use_block
GRID_FLAG=""
BLOCK_FLAG=""

if [ "$USE_GRID" -eq 1 ]; then
  GRID_FLAG="--use_grid"
fi

if [ "$USE_BLOCK" -eq 1 ]; then
  BLOCK_FLAG="--use_block"
fi

# Run the training script with specified hyperparameters
python /home/mcs001/20181133/CLAM/main.py \
  --drop_out 0.25 \
  --lr $LR \
  --reg $REG \
  --window_size $WINDOW_SIZE \
  --k 1 \
  --exp_code $EXP_CODE \
  --weighted_sample \
  --bag_loss ce \
  $GRID_FLAG \
  $BLOCK_FLAG \
  --task task_1_tumor_vs_normal \
  --model_type gabmil \
  --data_root_dir /home/mcs001/20181133/CLAM/data_feat \
  --root_sub_dir Camelyon16_patch256_ostu_res50_pl1_wsi \
  --results_dir /home/mcs001/20181133/CLAM/results/hyperopt \
  --split_dir /home/mcs001/20181133/CLAM/splits/task_camelyon16_wsi \
  --embed_dim 1024

# Capture validation loss from the output file generated by the script
VAL_LOSS_FILE="/home/mcs001/20181133/CLAM/results/hyperopt/${EXP_CODE}_s${SEED}/output_metric.txt"

# Write the validation loss to the RESULT_FILE for the Bayesian optimizer
if [ -f "$VAL_LOSS_FILE" ]; then
  VAL_LOSS=$(cat $VAL_LOSS_FILE)
  echo "$VAL_LOSS" > "$RESULT_FILE"
else
  echo "9999.0" > "$RESULT_FILE"  # High penalty for failure
fi

